[package]
name = "sidebar_slint"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = "thin"

[dependencies]
active-win-pos-rs = "0.7.1"
chrono = "0.4.23"
ctrlc = "3.2.5"
eframe = "0.21.3"
human_bytes = "0.4.1"
itertools = "0.10.5"
lazy_static = "1.4.0"
sysinfo = "0.28.2"
windows = { version = "0.44.0", features = ["Win32_UI_Shell", "Win32_Foundation", "Win32_Graphics_Dwm", "Win32_UI_WindowsAndMessaging"] }
winreg = "0.11.0"
# slint = "0.3.5"
